### ISSUE TITLE
PrismaClient 초기화

### ISSUE THREAD

**Issue by NohJanghan** [NohJanghan/GIST-HOUSE-WEB-BE#6]
## Overview
prisma를 사용하는 각 파일에서 `const prisma = new prismaClient()`와 같이 작성하면 여러개의 prismaClient가 초기화되어서 좋지 않다. 한 번에 연결할 수 있는 prisma client 수에는 제한이 있고, prisma를 연결하고 연결을 해제하는 과정은 시간이 많이 들기 때문이다. 공식 문서에서는 Long-running process는 앱 전체에 걸쳐서 하나의 prismaClient를 사용하기를 권장하고 있다.

> ✔ Create one instance of PrismaClient and re-use it across your application
✔ Assign PrismaClient to a global variable in dev environments only to prevent hot reloading from creating new instances
[From here](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections#prismaclient-in-long-running-applications)

따라서 이 권장사항을 지키기 위해서 `./prismaClient.js`에서 prisma client를 초기화하고, 다른 위치에서는 `const prisma = require('./prismaClient'`와 같이 접근하도록 한다.
또한, 개발 환경에서는 핫 리로드시에 새로운 prisma client를 만들지 않도록 global variable로 할당해야한다.

## TODO
- [x] Prisma client를 초기화하는 `./prismaClient.js` 생성
- [x] 개발환경에서는 prisma client를 전역 변수로 설정하여 핫 리로딩시에도 새로운 인스턴스를 사용하지 않도록 해야함.
- [x] (Conditional) 다른 파일에서 `const prisma = new prismaClient()`와 같이 새로 초기화하는 부분이 있다면, `./prismaClient.js`에 있는 prisma client를 사용하도록 변경
